### ISSUE TITLE
No crosshairs for rocketlaunchers?

### ISSUE THREAD

**Issue by insomniaa1** [mkrl/cfgtf#56] opened 2018-08-19 21:42 UTC
So, when I downloaded the weapon especific crosshairs, stuff like tf_weapon_rocketlaucher.txt are missing, the weapons I found missing are : The Rocketlauncher, Cowmangler 5000, Direct Hit, Airstrike, Beggar's Bazooka and The Original, basically all the soldier primaries

**Comment by InsightAbe05** [comment] 2018-08-20 23:59
same here

**Comment by mkrl** [comment] 2018-11-14 03:34
Duplicate of https://github.com/mkrl/cfgtf/issues/44

**Closed as completed by mkrl** 2018-11-14 03:34 UTC
