### ISSUE TITLE
Crosshair Issue Weapon-specific

### ISSUE THREAD

**Issue by Thawss** [mkrl/cfgtf#55] opened 2018-08-18 23:10 UTC
Um i was using cfg.tf for 2 days now but there was a problem i run into when i try to download a directhit 
one and the grenade luncher there is no script when i open the crosshair file in winrar pls fix it

**Comment by mkrl** [comment] 2018-11-14 03:34
Duplicate of https://github.com/mkrl/cfgtf/issues/44

**Closed as completed by mkrl** 2018-11-14 03:34 UTC
